"""empty message

Revision ID: 489c4dab6e63
Revises: 3aa560ed68d1
Create Date: 2025-02-23 22:42:51.124506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489c4dab6e63'
down_revision = '3aa560ed68d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_planets_planet_id_key', type_='unique')
        batch_op.drop_constraint('favorite_planets_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorite_planets_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('favorite_planets_planet_id_key', ['planet_id'])

    # ### end Alembic commands ###
